apiVersion: apps/v1
kind: Deployment
metadata:
  name: logoutput
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  randomstringgenerator
  template:
    metadata:
      labels:
        app:  randomstringgenerator
    spec:
      containers:
        - name:  logoutput
          image: anniinasainio/randomstringgenerator:v3.0 
